<a href="https://colab.research.google.com/github/Soma-123/PROJECTS-ML-/blob/main/ENSEBLE_LEARNING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ENSEMBLE LEARNING


---



---



In [10]:
from sklearn.datasets import load_iris

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import train_test_split

In [11]:

iris=load_iris()
x=iris.data
y=iris.target

df=pd.DataFrame(x,columns=iris.feature_names)
df['target']=y
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [12]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
clf=RandomForestClassifier(n_estimators=100,random_state=42)
clf.fit(X_train,Y_train)

RandomForestClassifier(random_state=42)

In [14]:
y_predict=clf.predict(X_test)

In [15]:
print("Confusion Matrix:\n",confusion_matrix(Y_test,y_predict))
print("classification report:\n",classification_report(Y_test,y_predict))

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# gradient Descent


---



---



In [16]:
from sklearn.datasets import fetch_california_housing
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error

In [18]:
data=fetch_california_housing()
x=data.data
y=data.target

In [19]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [20]:
gbr=GradientBoostingRegressor(n_estimators=100,learning_rate=0.1,max_depth=3,random_state=42)
gbr.fit(X_train,Y_train)

GradientBoostingRegressor(random_state=42)

In [21]:
y_pred=gbr.predict(X_test)

In [22]:
mse=mean_squared_error(Y_test,y_pred)
r2=r2_score(Y_test,y_pred)
print(mse)
print(r2)


0.2939973248643864
0.7756446042829697


# ADA BOOST

---



---



In [36]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,classification_report

In [37]:
iris=load_iris()
x=iris.data
y=iris.target

df=pd.DataFrame(x,columns=iris.feature_names)
df['target']=y
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [38]:
x=x[y!=2]
y=y[y!=2]

In [39]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [40]:
base_estimator=DecisionTreeClassifier(max_depth=1)

In [41]:
adaboost=AdaBoostClassifier(estimator=base_estimator,n_estimators=50,learning_rate=1,random_state=42)

In [42]:
adaboost.fit(X_train,Y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   learning_rate=1, random_state=42)

In [43]:
y_pred=adaboost.predict(X_test)

In [45]:
ac=accuracy_score(Y_test,y_pred)
cr=classification_report(Y_test,y_pred)

In [46]:
print(f"Accuracy score is {ac}")

Accuracy score is 1.0


In [47]:
print(f"classification report is {cr}")

classification report is               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

